# ./docker-compose.yml

version: '3.3'
services:
    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
        ports:
            - 27017:27017
        command: [--auth]
        container_name: mongodb
    server:
        image: mongo-express
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
        ports:
            - 47000:47000   # main database
        volumes:
            - ./:/workspace
        links: 
            - mongodb
        depends_on:
            - mongodb
        working_dir: /workspace
        command: node server.js
        container_name: server 


